/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Fase3 extends javax.swing.JFrame {

    boolean c1,c2,c3,c4;
    private int pontos1,pontos2,pontos3,pontos4,somafase3;
    public Fase3() {
        initComponents();
        pontos1=pontos2=pontos3=pontos4=somafase3=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ibt1fase3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ibt5fase3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ibt2fase3 = new javax.swing.JLabel();
        ibt4fase3 = new javax.swing.JLabel();
        ibt3fase3 = new javax.swing.JLabel();
        ibtr4fase3 = new javax.swing.JLabel();
        ibtr1fase3 = new javax.swing.JLabel();
        ibtr2fase3 = new javax.swing.JLabel();
        ibtr3fase3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3includer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3return.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 250, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3intr.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 220, 80));

        ibt1fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3charr.png"))); // NOI18N
        ibt1fase3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ibt1fase3MouseDragged(evt);
            }
        });
        getContentPane().add(ibt1fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3printf1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3printf2.png"))); // NOI18N
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3printf3.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3printf4.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        ibt5fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3printf4.png"))); // NOI18N
        getContentPane().add(ibt5fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3scanf.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        ibt2fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3if.png"))); // NOI18N
        ibt2fase3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ibt2fase3MouseDragged(evt);
            }
        });
        getContentPane().add(ibt2fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        ibt4fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3else.png"))); // NOI18N
        ibt4fase3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ibt4fase3MouseDragged(evt);
            }
        });
        getContentPane().add(ibt4fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        ibt3fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/f3elseif.png"))); // NOI18N
        ibt3fase3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ibt3fase3MouseDragged(evt);
            }
        });
        getContentPane().add(ibt3fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        ibtr4fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ibtr4fase3MouseEntered(evt);
            }
        });
        getContentPane().add(ibtr4fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 220, 60));

        ibtr1fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ibtr1fase3MouseEntered(evt);
            }
        });
        getContentPane().add(ibtr1fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 220, 70));

        ibtr2fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ibtr2fase3MouseEntered(evt);
            }
        });
        getContentPane().add(ibtr2fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 220, 60));

        ibtr3fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ibtr3fase3MouseEntered(evt);
            }
        });
        getContentPane().add(ibtr3fase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 220, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/enunciadof3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 820, 430));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/botãoproximafase.png"))); // NOI18N
        jButton1.setText("PROXIMA FASE");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 660, 230, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/menuinfob.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/fundoatt.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1980, 1020));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, 1240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ibt1fase3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibt1fase3MouseDragged
       ibt1fase3.setLocation(ibt1fase3.getX()+evt.getX(), ibt1fase3.getY()+evt.getY());
        c1=true; 
    }//GEN-LAST:event_ibt1fase3MouseDragged

    private void ibt2fase3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibt2fase3MouseDragged
       ibt2fase3.setLocation(ibt2fase3.getX()+evt.getX(), ibt2fase3.getY()+evt.getY());
       c2=true; 
    }//GEN-LAST:event_ibt2fase3MouseDragged

    private void ibt4fase3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibt4fase3MouseDragged
       ibt4fase3.setLocation(ibt4fase3.getX()+evt.getX(), ibt4fase3.getY()+evt.getY());
       c3=true; 
    }//GEN-LAST:event_ibt4fase3MouseDragged

    private void ibt3fase3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibt3fase3MouseDragged
       ibt3fase3.setLocation(ibt3fase3.getX()+evt.getX(), ibt3fase3.getY()+evt.getY());
       c4=true; 
    }//GEN-LAST:event_ibt3fase3MouseDragged

    private void ibtr1fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibtr1fase3MouseEntered
        if(c1){
           ibt1fase3.setVisible(false);
           ibtr1fase3.setIcon(new ImageIcon("src/resouces/f3charr_1.png"));
           pontos1=1;
           
       }
    }//GEN-LAST:event_ibtr1fase3MouseEntered

    private void ibtr2fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibtr2fase3MouseEntered
        if(c2){
           ibt2fase3.setVisible(false);
           ibtr2fase3.setIcon(new ImageIcon("src/resouces/f3if.png"));
           pontos2=1;
           
       }
    }//GEN-LAST:event_ibtr2fase3MouseEntered

    private void ibtr3fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibtr3fase3MouseEntered
        if(c4){
           ibt3fase3.setVisible(false);
           ibtr3fase3.setIcon(new ImageIcon("src/resouces/f3elseif.png"));
           pontos3=1;
           
       }
    }//GEN-LAST:event_ibtr3fase3MouseEntered

    private void ibtr4fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibtr4fase3MouseEntered
         if(c3){
           ibt4fase3.setVisible(false);
           ibtr4fase3.setIcon(new ImageIcon("src/resouces/f3else.png"));
           pontos4=1;
           
       }
    }//GEN-LAST:event_ibtr4fase3MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        somafase3=pontos1+pontos2+pontos3+pontos4;
        
         if(somafase3==4){
            Creditos creditos = new Creditos();
            creditos.setVisible(true);
            dispose();
            creditos=null;
          }else{
            String somafase2 = null;
             JOptionPane.showMessageDialog(null, " - Pontos insuficientes - "+somafase2); 
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       MenuInfof3 menuinfof3 = new MenuInfof3();
       menuinfof3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
   public void Verificacaofase3(){
        somafase3=pontos1+pontos2+pontos3+pontos4;
        if(somafase3==4){
             JOptionPane.showMessageDialog(null, " - Parabens - "+somafase3); 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ibt1fase3;
    private javax.swing.JLabel ibt2fase3;
    private javax.swing.JLabel ibt3fase3;
    private javax.swing.JLabel ibt4fase3;
    private javax.swing.JLabel ibt5fase3;
    private javax.swing.JLabel ibtr1fase3;
    private javax.swing.JLabel ibtr2fase3;
    private javax.swing.JLabel ibtr3fase3;
    private javax.swing.JLabel ibtr4fase3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label8;
    // End of variables declaration//GEN-END:variables
}
