/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DTO.RegistroNome;




/**
 *
 * @author aluno
 */
public class TelaIniciar extends javax.swing.JFrame {
    
    
    /**
     * Creates new form TelaIniciar
     */
    
    
    public TelaIniciar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntSair0 = new javax.swing.JButton();
        btnstart = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        i = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntSair0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/pixil-frame-0.png"))); // NOI18N
        bntSair0.setBorderPainted(false);
        bntSair0.setContentAreaFilled(false);
        bntSair0.setFocusPainted(false);
        bntSair0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSair0ActionPerformed(evt);
            }
        });
        getContentPane().add(bntSair0, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        btnstart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/buttonplay.png"))); // NOI18N
        btnstart.setBorderPainted(false);
        btnstart.setContentAreaFilled(false);
        btnstart.setFocusPainted(false);
        btnstart.setFocusable(false);
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });
        getContentPane().add(btnstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 290, 150));

        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 580, 60));

        i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/MicrosoftTeams-image.png"))); // NOI18N
        i.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        RegistroNome  registronome= new RegistroNome();
        registronome.setNome(txtNome.getText());
        Menu Menu = new Menu();
        Menu.exportarNome(registronome);
        Menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnstartActionPerformed

    private void bntSair0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSair0ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bntSair0ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSair0;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel i;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
